import { useState } from 'react';
import { CheckCircle2, FilePenLine, Users, RotateCcw } from 'lucide-react';
import { DemoCase } from './data/demoCases';
type Props = { cases: DemoCase[]; update: (id: string, patch: Partial<Pick<DemoCase, 'actions' | 'draft' | 'reviewed' | 'closed'>>) => void; reset: () => void };

export default function OperationalApp({ cases, update, reset }: Props) {
  const [role, setRole] = useState('profesional'); const [personId, setPersonId] = useState(cases[0].id);
  const [query, setQuery] = useState(''); const [showDraft, setShowDraft] = useState(false); const [notice, setNotice] = useState('');
  const filtered = cases.filter(c => `${c.name} ${c.id} ${c.program}`.toLowerCase().includes(query.toLowerCase()));
  const selected = filtered.find(c => c.id === personId) ?? filtered[0] ?? cases[0];
  const latest = selected.sessions[selected.sessions.length - 1];
  const isProfessional = role === 'profesional';
  const overview = role === 'bienestar' ? cases : cases.filter(c => c.program === role);
  return <section className="professional-panel" aria-label="Panel de demostración">
    <div className="panel-toolbar"><label htmlFor="demo-role">Rol de demostración<select id="demo-role" value={role} onChange={e => { setRole(e.target.value); setShowDraft(false); setNotice(''); }}><option value="profesional">Profesional de acompañamiento</option><option value="Ingeniería">Responsable de programa · Ingeniería</option><option value="Derecho">Responsable de programa · Derecho</option><option value="Medicina">Responsable de programa · Medicina</option><option value="bienestar">Responsable de área · Bienestar</option></select></label><button className="secondary" onClick={() => { if (confirm('¿Restablecer únicamente los cambios de esta demostración ficticia?')) { reset(); setNotice('Ejemplos ficticios restablecidos.'); } }}><RotateCcw size={16} />Restablecer ejemplo</button></div>
    <div className="demo-note">Simulación de vistas por rol. Ocultar campos en el navegador no controla el acceso: los datos ficticios están en el dispositivo. El acceso real y el cambio de responsable requieren una política y controles de servidor por definir.</div>
    <p className="section-intro">Información orientada al cuidado y al apoyo. La vista individual se diseña para el profesional autorizado; la selección de arriba no autentica usuarios.</p>
    {notice && <p role="status" className="decision-box">{notice}</p>}
    {isProfessional ? <><div className="catalog-tools"><label className="search">Buscar<input aria-label="Buscar caso ficticio" placeholder="Nombre, identificador o programa" value={query} onChange={e => { setQuery(e.target.value); setShowDraft(false); setNotice(''); }} /></label><span className="muted">{filtered.length} {filtered.length === 1 ? 'persona ficticia' : 'personas ficticias'}</span></div><div className="filters case-filters">{filtered.map(c => <button key={c.id} className={selected.id === c.id ? 'selected' : ''} aria-pressed={selected.id === c.id} onClick={() => { setPersonId(c.id); setShowDraft(false); setNotice(''); }}>{c.name} · {c.program}</button>)}</div>
      {filtered.length === 0 ? <p className="empty-state">No hay casos con esa búsqueda.</p> : <article className="professional-case"><span className="eyebrow">EJEMPLO FICTICIO · {selected.id} · {selected.closed ? 'CIERRE SIMULADO' : 'EN SEGUIMIENTO'}</span><h2>{selected.name}: {selected.need}</h2><div className="evidence-columns"><div><h3>Lo expresado por la persona</h3><blockquote>“{latest.said}”</blockquote></div><div><h3>Observación del profesional</h3><p>{latest.observed}</p></div><div><h3>Señal pendiente de valoración</h3><p>{selected.signal}</p></div></div>
        <h3>Acuerdos de acompañamiento</h3><div className="action-checklist">{selected.actions.map(a => <label key={a.id}><input type="checkbox" checked={a.done} onChange={e => update(selected.id, { actions: selected.actions.map(item => item.id === a.id ? { ...item, done: e.target.checked } : item) })} /><span>{a.text}<small>{a.owner} · {a.done ? 'Completado en la simulación' : 'Pendiente'}</small></span></label>)}</div>
        <div className="hero-actions"><button className="primary" onClick={() => setShowDraft(!showDraft)} aria-expanded={showDraft}><FilePenLine size={17} />{showDraft ? 'Ocultar borrador' : 'Revisar borrador de mensaje'}</button><button className="secondary" disabled={!selected.closed && selected.actions.some(a => !a.done)} onClick={() => { update(selected.id, { closed: !selected.closed }); setNotice(selected.closed ? 'Seguimiento reabierto en la simulación.' : 'Cierre guardado solo en la simulación. No se emite certificado ni se cambia una obligación académica.'); }}>{selected.closed ? 'Reabrir seguimiento simulado' : 'Simular cierre del seguimiento'}</button></div><p className="field-help">El cierre del ejemplo se habilita al completar los acuerdos. Su uso real requiere criterios institucionales por definir.</p>
        {showDraft && <section className="draft-editor"><h3>Borrador para revisión del profesional</h3><p>{selected.reviewed ? 'Revisado en esta demostración · No enviado' : 'Pendiente de revisión · No enviado'}</p><label htmlFor="message-draft">Texto del ejemplo</label><textarea id="message-draft" rows={5} value={selected.draft} onChange={e => update(selected.id, { draft: e.target.value, reviewed: false })} /><button className="primary" disabled={!selected.draft.trim()} onClick={() => { update(selected.id, { reviewed: true }); setNotice('Borrador marcado como revisado en este navegador. No se ha enviado ninguna comunicación.'); }}><CheckCircle2 size={17} />Marcar como revisado</button><p className="field-help">Canal de envío e integración pendientes. Este botón solo guarda la revisión local.</p></section>}
      </article>}
    </> : <section className="role-overview"><Users size={30} /><h2>Información para revisión del área</h2><p>Propuesta ilustrativa de una vista sin relatos individuales. Los responsables definen qué información necesitan; el equipo de Analítica construye el análisis.</p><div className="stats benefits"><div><strong>{overview.length}</strong><p>Personas ficticias del ejemplo</p></div><div><strong>{overview.reduce((n, c) => n + c.actions.filter(a => !a.done).length, 0)}</strong><p>Acuerdos pendientes de la simulación</p></div></div>{overview.length === 0 && <p className="empty-state">No se han incluido casos ficticios para este programa.</p>}<div className="decision-box"><strong>Salida posible: aviso de actualización del tablero</strong><p>El responsable del área revisaría la información antes de definir apoyos. Aviso ilustrativo, no enviado; sin cifras de impacto ni garantías de anonimización.</p></div></section>}
  </section>;
}
