import { useEffect, useState } from 'react';
import { AudioLines, ArrowRight, ChevronLeft, ChevronRight, Play, Pause, Maximize2, Video, X, MessageCircle, FileText, Database, Users, HeartHandshake, ShieldCheck, ScanLine, UserCheck, GraduationCap, BriefcaseBusiness, Presentation, Building2, Handshake, Orbit } from 'lucide-react';
import { ConversationOffice } from './ConversationOffice';
import '../pitch-motion.css';
import { audiences } from '../data/audiences';

const scenes = [
  { title: 'La conversación', duration: 35, label: 'El contexto humano', heading: 'Sabemos qué pasó. ¿Conservamos el porqué?', lead: 'Cada encuentro deja algo más que un registro.', notes: 'Presentar a Mateo como un caso ficticio. Su conversación reúne preocupaciones académicas y preguntas sobre su beca. La oportunidad está en conectar ese contexto entre los puntos de contacto existentes, sin dar por hecho que hoy no haya registros.' },
  { title: 'La oportunidad', duration: 30, label: 'El cuidado empieza al escuchar', heading: 'Escuchar. Registrar. Volver a empezar.', lead: 'Cuando el contexto se dispersa, reconstruir la historia exige atención y esfuerzo.', notes: 'Explicar la tensión entre escuchar y registrar. El registro manual o disperso puede dificultar el siguiente encuentro. No presentar tiempos de ahorro como resultados medidos.' },
  { title: 'ResonancIA', duration: 35, label: 'Memoria institucional activa', heading: 'Que lo conversado se convierta en conocimiento.', lead: 'Escucha, comprensión y realimentación en un ciclo continuo.', notes: 'Presentar ResonancIA y el ciclo del mockup: interacción, captura, memoria, analítica, decisión, activación, resultado y realimentación. El registro requiere autorización. La IA extrae y organiza; el equipo humano interpreta y decide.' },
  { title: 'Doble cuidado', duration: 35, label: 'Para quien habla. Para quien escucha.', heading: 'Más presencia. Más continuidad.', lead: 'Cuidar a la persona y apoyar al profesional que la acompaña.', notes: 'Mostrar el beneficio esperado: atención a la conversación, registro asistido y contexto para el siguiente encuentro. Se busca reducir la carga operativa y facilitar una pausa entre atenciones; todavía debe evaluarse en la práctica.' },
  { title: 'Cinco públicos', duration: 45, label: 'Una lógica, distintas aplicaciones', heading: 'Toda una comunidad. Muchas formas de acompañar.', lead: 'La metodología se adapta al proceso, a sus fuentes y a sus responsables.', notes: 'Recorrer los cinco públicos. Graduados: formación a lo largo de la vida. Aliados: necesidades del entorno y capacidades de la Universidad. Profesores y administrativos: acompañamiento y memoria de gestión. Estos modelos están documentados; no se presentan como integraciones activas.' },
  { title: 'Detrás del diálogo', duration: 45, label: 'Agentes coordinados, funciones claras', heading: 'Del diálogo a la información organizada.', lead: 'El orquestador coordina. Los especialistas estructuran y revisan.', notes: 'Mostrar el caso de asesoría psicopedagógica: captura, orquestación, fichas temáticas, revisión y memoria. Los robots y los paquetes muestran una coordinación ilustrativa; no es telemetría en vivo. Tras la estructuración, el equipo de Analítica trabaja con el responsable.' },
  { title: 'La confianza', duration: 40, label: 'Principios que orientan el diseño', heading: 'La información sirve para cuidar.', lead: 'Escuchar con confianza. Interpretar con contexto. Decidir con responsabilidad.', notes: 'Explicar los principios: autorización antes de registrar, evidencia para revisar, acceso según responsabilidad y decisión humana. Los controles y las políticas institucionales requieren definición y validación antes de usar datos reales.' },
  { title: 'El siguiente paso', duration: 35, label: 'Con voz transformamos', heading: 'Con memoria cuidamos.', lead: 'Amplificar nuestra capacidad de escuchar, comprender y actuar mejor.', notes: 'Cerrar con la propuesta de experimentar de manera acompañada, revisar resultados y evolucionar el diseño. El prototipo permite explorar el modelo y sus especificaciones; invitar a recorrer el panel profesional después del pitch.' },
];
const starts = scenes.map((_, i) => scenes.slice(0, i).reduce((sum,s) => sum+s.duration,0));
const clock = (value: number) => `${Math.floor(value/60)}:${String(value%60).padStart(2,'0')}`;
const cycle = ['Interacción','Captura','Memoria','Analítica','Decisión','Activación','Resultado','Realimentación'];
const audienceIcons = [GraduationCap, BriefcaseBusiness, Presentation, Building2, Handshake];

function ProcessVisual({ connected = false }: { connected?: boolean }) {
  return <div className={`pitch-process ${connected ? 'connected' : ''}`}><div className="process-person"><Users size={38}/><strong>Mateo</strong><span>Caso ficticio</span></div><div className="process-stations">{['Admisiones','Bienestar','Asesoría','Becas'].map((s,i)=><div className="process-station" key={s}><span>0{i+1}</span><MessageCircle size={23}/><strong>{s}</strong><small>{connected ? 'Contexto para acompañar' : 'Una parte de la historia'}</small></div>)}</div><div className="context-thread"><Database size={21}/><span>{connected ? 'Memoria institucional · continuidad según permisos por definir' : 'El contexto puede quedar disperso entre registros y personas'}</span></div></div>;
}

export function PitchStage({ recording, onRecording, onInspect, onPanel }: { recording: boolean; onRecording: (value:boolean)=>void; onInspect:(id:string)=>void; onPanel:()=>void }) {
  const [take,setTake]=useState(0);
  const [scene,setScene]=useState(0); const [elapsed,setElapsed]=useState(0); const [playing,setPlaying]=useState(false); const [notes,setNotes]=useState(false); const [cycleStep,setCycleStep]=useState(0); const [audience,setAudience]=useState(0); const [full,setFull]=useState(false); const [notice,setNotice]=useState('');
  const jump=(index:number)=>{setScene(index);setElapsed(starts[index]);setPlaying(false);window.scrollTo({top:0,behavior:'instant'});};
  useEffect(()=>{if(!playing)return;const timer=setInterval(()=>{if(!document.hidden)setElapsed(t=>Math.min(300,t+1));},1000);return()=>clearInterval(timer);},[playing]);
  useEffect(()=>{if(!playing)return;if(elapsed>=300){setPlaying(false);return;}const index=starts.findIndex((start,i)=>elapsed>=start && elapsed<start+scenes[i].duration);if(index>=0)setScene(index);},[elapsed,playing]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement||document.querySelector('dialog[open]'))return;if(e.key==='Escape'){onRecording(false);setPlaying(false);}if(e.key==='ArrowRight'){e.preventDefault();setScene(s=>{const next=Math.min(7,s+1);setElapsed(starts[next]);return next;});setPlaying(false);}if(e.key==='ArrowLeft'){e.preventDefault();setScene(s=>{const next=Math.max(0,s-1);setElapsed(starts[next]);return next;});setPlaying(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[onRecording]);
  useEffect(()=>{const sync=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',sync);return()=>document.removeEventListener('fullscreenchange',sync);},[]);
  async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setNotice('Continúa el pitch en esta ventana; pantalla completa no está disponible.');}}
  const current=scenes[scene], a=audiences[audience];
  return <section className="pitch-stage"><div className="pitch-tools"><div><span className="eyebrow">PITCH · GUION PARA VIDEO</span><small>8 escenas · 5 minutos de pauta</small></div><div><button className="text-button" onClick={()=>setTake(t=>t+1)}>Repetir animación</button><button className="text-button" onClick={()=>setNotes(!notes)} aria-pressed={notes}>{notes?'Ocultar guion':'Notas de locución'}</button><button className="secondary" onClick={fullscreen}><Maximize2 size={16}/>{full?'Salir de pantalla completa':'Pantalla completa'}</button><button className="primary" onClick={()=>{setNotes(false);setTake(t=>t+1);onRecording(true);}}><Video size={16}/>Modo grabación</button></div></div>
    {notice&&<p role="status">{notice}</p>}
    <div key={`${scene}-${take}`} className={`pitch-screen pitch-motion scene-${scene}`}><header className="pitch-brand"><AudioLines size={27}/><strong>ResonancIA</strong><span>UNIVERSIDAD DE LA SABANA · RETO DEL RECTOR</span></header><div className="pitch-heading"><span className="eyebrow">{current.label}</span><h1 aria-label={current.heading}>{current.heading.split(" ").map((word,i)=><span className="pitch-word-mask" aria-hidden="true" key={i}><span style={{animationDelay:`${.15+i*.075}s`}}>{word}</span>{" "}</span>)}</h1><p>{current.lead}</p></div>
      <div className="pitch-visual" key={scene}>
        {scene===0&&<><div className="pitch-quote"><span>LA VOZ DE MATEO · EJEMPLO FICTICIO</span><p>“Me fue mal en una materia y me preocupa qué pueda pasar con mi beca.”</p></div><ProcessVisual/></>}
        {scene===1&&<div className="attention-grid"><article><MessageCircle size={42}/><span>EN EL ENCUENTRO</span><h2>Escuchar con atención.</h2><p>Comprender lo que la persona necesita.</p></article><div className="attention-divider">+</div><article><FileText size={42}/><span>DESPUÉS DEL ENCUENTRO</span><h2>Conservar el contexto.</h2><p>Registrar, conectar y retomar los acuerdos.</p></article><div className="attention-conclusion">La oportunidad: apoyar el registro para dar continuidad al cuidado.</div></div>}
        {scene===2&&<div className="pitch-cycle"><div className="cycle-orbit"><div className="cycle-core"><Orbit size={45}/><span>MEMORIA<br/>INSTITUCIONAL</span></div>{cycle.map((name,i)=><button key={name} className={cycleStep===i?'active':''} style={{left:`${50+39*Math.cos((i*45-90)*Math.PI/180)}%`,top:`${50+39*Math.sin((i*45-90)*Math.PI/180)}%`}} onClick={()=>setCycleStep(i)} aria-pressed={cycleStep===i}><span>0{i+1}</span>{name}</button>)}</div><div className="cycle-caption"><span className="eyebrow">EL CICLO DE VALOR · 0{cycleStep+1}</span><h2>{cycle[cycleStep]}</h2><p>{['Una conversación que ya sucede.','Captura y estructuración con autorización.','Contexto organizado para retomar.','El equipo de Analítica construye información útil.','El responsable interpreta y decide.','Se ponen en marcha las acciones acordadas.','Se revisa lo que ocurrió con la acción.','El aprendizaje alimenta el siguiente encuentro.'][cycleStep]}</p><div className="pitch-formula">La IA extrae <ArrowRight size={15}/> La persona interpreta <ArrowRight size={15}/> La institución decide</div></div></div>}
        {scene===3&&<><div className="care-pair"><article><HeartHandshake size={33}/><span>QUIEN ES ESCUCHADO</span><h2>Su historia continúa.</h2><p>Acuerdos, antecedentes y pendientes para el siguiente encuentro.</p></article><article><UserCheck size={33}/><span>QUIEN ACOMPAÑA</span><h2>Su criterio permanece.</h2><p>Apoyo al registro y contexto disponible para orientar la conversación.</p></article></div><ProcessVisual connected/></>}
        {scene===4&&<div className="pitch-audiences"><div className="pitch-audience-tabs">{audiences.map((item,i)=>{const Icon=audienceIcons[i];return <button key={item.id} className={i===audience?'active':''} aria-pressed={i===audience} onClick={()=>setAudience(i)}><Icon size={23}/>{item.title}<ArrowRight size={16}/></button>;})}</div><article><span className="eyebrow">{a.title}</span><h2>{a.benefit}</h2><p>{a.need}</p><div className="audience-output"><small>REALIMENTACIÓN POSIBLE</small><strong>{a.output}</strong><p>Decide: {a.owner}.</p></div><small>Modelo documentado · Ejemplo ilustrativo</small></article></div>}
        {scene===5&&<ConversationOffice compact onInspect={id=>{setPlaying(false);onInspect(id);}}/>}
        {scene===6&&<><div className="trust-grid">{[{Icon:AudioLines,title:'Autorizar',text:'Explicar el registro antes de capturar.'},{Icon:ScanLine,title:'Sustentar',text:'Volver a la fuente para revisar los hallazgos.'},{Icon:ShieldCheck,title:'Cuidar',text:'Definir el acceso según la responsabilidad.'},{Icon:UserCheck,title:'Decidir',text:'El responsable interpreta y valida las acciones.'}].map(item=><article key={item.title}><item.Icon size={35}/><h2>{item.title}</h2><p>{item.text}</p></article>)}</div><div className="trust-line">Acompañar, orientar y mejorar la experiencia.<br/><strong>La confianza es parte del diseño.</strong></div></>}
        {scene===7&&<div className="pitch-closing"><div className="closing-orbit"><AudioLines size={70}/></div><h2>Escuchar.<br/>Comprender.<br/><em>Transformar.</em></h2><div className="closing-steps"><span>Exploramos</span><ArrowRight size={18}/><span>Experimentamos</span><ArrowRight size={18}/><span>Evolucionamos</span></div>{!recording&&<button className="primary" onClick={onPanel}>Explorar el panel profesional <ArrowRight size={17}/></button>}</div>}
      </div><footer className="pitch-screen-footer"><span>CON VOZ TRANSFORMAMOS</span><span>{scene===5?'Oficina de agentes · Simulación ilustrativa':scene===6?'Principios de diseño · Controles por implementar':'Demostración ilustrativa · Sin captura ni envío real'}</span><span>{String(scene+1).padStart(2,'0')} / 08</span></footer>
    </div>
    {notes&&!recording&&<aside className="speaker-notes"><span className="eyebrow">LOCUCIÓN · {clock(starts[scene])}—{clock(starts[scene]+current.duration)}</span><p>{current.notes}</p><small>Adaptación del guion actualizado del repositorio. Las duraciones son una pauta para ensayar.</small></aside>}
    <nav className="pitch-timeline" aria-label="Escenas del pitch">{scenes.map((s,i)=><button key={s.title} className={scene===i?'active':''} aria-current={scene===i?'step':undefined} onClick={()=>jump(i)}><small>{clock(starts[i])}</small><span>{s.title}</span></button>)}</nav>
    <div className="pitch-controls"><button className="text-button" disabled={scene===0} onClick={()=>jump(scene-1)}><ChevronLeft size={19}/>Anterior</button><div><span>{clock(elapsed)} / 5:00</span><button className="secondary" onClick={()=>{if(elapsed>=300){setElapsed(0);setScene(0);}setPlaying(!playing);}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pausar pauta':'Reproducir pauta'}</button></div><button className="text-button" onClick={()=>jump(scene===7?0:scene+1)}>{scene===7?'Reiniciar':'Siguiente'}<ChevronRight size={19}/></button></div>
    {recording&&<button className="exit-recording" onClick={()=>onRecording(false)}><X size={16}/>Salir del modo grabación <kbd>Esc</kbd></button>}
  </section>;
}
