import { useEffect, useState } from 'react';
import { AudioLines, ArrowRight, ChevronLeft, ChevronRight, Play, Pause, Maximize2, Video, X, MessageCircle, Database, Users, ShieldCheck, ScanLine, UserCheck, GraduationCap, BriefcaseBusiness, Presentation, Building2, Handshake } from 'lucide-react';
import { ConversationOffice } from './ConversationOffice';
import '../pitch-motion.css';
import { pitchScenes as scenes } from '../data/pitchScenes';
import { PitchIntro, PitchFlow, PitchBenefits, pitchAudiences } from './PitchVisuals';
import '../pitch-module-two.css';
import '../pitch-cinematic.css';

const starts = scenes.map((_, i) => scenes.slice(0, i).reduce((sum,s) => sum+s.duration,0));
// Conserva las clases visuales aprobadas, incluida la oficina, al reordenar el guion.
const sceneStyles = [2, 0, 3, 4, 5, 6, 7];
const clock = (value: number) => `${Math.floor(value/60)}:${String(value%60).padStart(2,'0')}`;
const audienceIcons = [GraduationCap, BriefcaseBusiness, Handshake, Presentation, Building2];

function ProcessVisual({ connected = false }: { connected?: boolean }) {
  return <div className={`pitch-process ${connected ? 'connected' : ''}`}><div className="process-person"><Users size={38}/><strong>Mateo</strong><span>Caso ficticio</span></div><div className="process-stations">{['Admisiones','Bienestar','Asesoría','Becas'].map((s,i)=><div className="process-station" key={s}><span>0{i+1}</span><MessageCircle size={23}/><strong>{s}</strong><small>{connected ? 'Contexto para acompañar' : 'Una parte de la historia'}</small></div>)}</div><div className="context-thread"><Database size={21}/><span>{connected ? 'Memoria institucional · continuidad según permisos por definir' : 'El contexto puede quedar disperso entre registros y personas'}</span></div></div>;
}

export function PitchStage({ recording, onRecording, onInspect, onPanel }: { recording: boolean; onRecording: (value:boolean)=>void; onInspect:(id:string)=>void; onPanel:()=>void }) {
  const [take,setTake]=useState(0);
  const [scene,setScene]=useState(0); const [elapsed,setElapsed]=useState(0); const [playing,setPlaying]=useState(false); const [notes,setNotes]=useState(false); const [audience,setAudience]=useState(0); const [full,setFull]=useState(false); const [notice,setNotice]=useState('');
  const jump=(index:number)=>{setScene(index);setElapsed(starts[index]);setPlaying(false);window.scrollTo({top:0,behavior:'instant'});};
  useEffect(()=>{if(!playing)return;const timer=setInterval(()=>{if(!document.hidden)setElapsed(t=>Math.min(300,t+1));},1000);return()=>clearInterval(timer);},[playing]);
  useEffect(()=>{if(!playing)return;if(elapsed>=300){setPlaying(false);return;}const index=starts.findIndex((start,i)=>elapsed>=start && elapsed<start+scenes[i].duration);if(index>=0)setScene(index);},[elapsed,playing]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement||document.querySelector('dialog[open]'))return;if(e.key==='Escape'){onRecording(false);setPlaying(false);}if(e.key==='ArrowRight'){e.preventDefault();setScene(s=>{const next=Math.min(scenes.length-1,s+1);setElapsed(starts[next]);return next;});setPlaying(false);}if(e.key==='ArrowLeft'){e.preventDefault();setScene(s=>{const next=Math.max(0,s-1);setElapsed(starts[next]);return next;});setPlaying(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[onRecording]);
  useEffect(()=>{const sync=()=>setFull(!!document.fullscreenElement);document.addEventListener('fullscreenchange',sync);return()=>document.removeEventListener('fullscreenchange',sync);},[]);
  useEffect(()=>{if(scene!==3||!playing)return;const seconds=elapsed-starts[3];setAudience(seconds<5?0:seconds<15?1:seconds<25?2:seconds<34?3:4);},[scene,elapsed,playing]);
  async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{setNotice('Continúa el pitch en esta ventana; pantalla completa no está disponible.');}}
  const current=scenes[scene], a=pitchAudiences[audience], AudienceIcon=audienceIcons[audience];
  return <section className="pitch-stage"><div className="pitch-tools"><div><span className="eyebrow">PITCH · GUION PARA VIDEO</span><small>{scenes.length} escenas · 5 minutos de pauta</small></div><div><button className="text-button" onClick={()=>setTake(t=>t+1)}>Repetir animación</button><button className="text-button" onClick={()=>setNotes(!notes)} aria-pressed={notes}>{notes?'Ocultar guion':'Notas de locución'}</button><button className="secondary" onClick={fullscreen}><Maximize2 size={16}/>{full?'Salir de pantalla completa':'Pantalla completa'}</button><button className="primary" onClick={()=>{setNotes(false);setTake(t=>t+1);onRecording(true);}}><Video size={16}/>Modo grabación</button></div></div>
    {notice&&<p role="status">{notice}</p>}
    <div key={`${scene}-${take}`} className={`pitch-screen pitch-motion scene-${sceneStyles[scene]}`}><header className="pitch-brand"><AudioLines size={27}/><strong>ResonancIA</strong><span>UNIVERSIDAD DE LA SABANA · RETO DEL RECTOR</span></header><div className="pitch-heading"><span className="eyebrow">{current.label}</span><h1 aria-label={current.heading}>{current.heading.split(" ").map((word,i)=><span className="pitch-word-mask" aria-hidden="true" key={i}><span style={{animationDelay:`${.15+i*.075}s`}}>{word}</span>{" "}</span>)}</h1><p>{current.lead}</p></div>
      <div className="pitch-visual" key={scene}>
        {scene===0&&<PitchIntro onPanel={onPanel} recording={recording}/>}
        {scene===1&&<><div className="pitch-case-row"><div className="pitch-quote"><span>LA VOZ DE MATEO · CASO FICTICIO</span><p>“Me está costando estudiar. En casa hay presión económica y me preocupa perder mi beca.”</p></div><div className="pitch-session-clock"><span>30</span><strong>MINUTOS</strong><small>Escuchar · Comprender · Registrar</small></div></div><ProcessVisual/></>}
        {scene===2&&<PitchFlow/>}
        {scene===3&&<div className="pitch-audiences"><div className="pitch-audience-tabs">{pitchAudiences.map((item,i)=>{const Icon=audienceIcons[i];return <button key={item.title} className={i===audience?'active':''} aria-pressed={i===audience} onClick={()=>{setAudience(i);setPlaying(false);}}><Icon size={23}/>{item.title}<ArrowRight size={16}/></button>;})}</div><article key={a.title}><AudienceIcon className="pitch-audience-symbol" aria-hidden="true"/><span className="eyebrow">{a.title}</span><h2>{a.benefit}</h2><div className="audience-output"><small>REALIMENTACIÓN POSIBLE</small><strong>{a.output}</strong></div><small>Ejemplo ilustrativo · Configurable por proceso</small></article></div>}
        {scene===4&&<ConversationOffice compact onInspect={id=>{setPlaying(false);onInspect(id);}}/>}
        {scene===5&&<><div className="trust-grid">{[{Icon:UserCheck,title:'Consentimiento',text:'Explicar y acordar el registro de la conversación.'},{Icon:ShieldCheck,title:'Acceso por roles',text:'Información disponible según la responsabilidad.'},{Icon:ScanLine,title:'Confidencialidad',text:'Anonimización y cuidado del contexto personal.'},{Icon:Users,title:'Criterio humano',text:'El profesional revisa, ajusta y decide.'}].map(item=><article key={item.title}><item.Icon size={35}/><h2>{item.title}</h2><p>{item.text}</p></article>)}</div><div className="trust-line">Acompañar, orientar y conectar.<br/><strong>Cuidar a las personas en cada encuentro.</strong></div><div className="pitch-trust-levels"><span>Personas</span><ArrowRight size={16}/><span>Procesos</span><ArrowRight size={16}/><span>Universidad</span></div></>}
        {scene===6&&<div className="pitch-new-closing"><div className="pitch-capabilities">{['Sin nuevos puntos de contacto','Escalable','Humano en el centro','Memoria institucional'].map(t=><span key={t}>{t}</span>)}</div><PitchBenefits/><div className="pitch-final-signature"><AudioLines size={34}/><strong>ResonancIA</strong><span>Escuchar → Comprender → Realimentar</span></div>{!recording&&<button className="primary" onClick={onPanel}>Explorar el panel profesional <ArrowRight size={17}/></button>}</div>}
      </div><footer className="pitch-screen-footer"><span>CON VOZ TRANSFORMAMOS</span><span>{scene===4?'Oficina de agentes · Simulación ilustrativa':scene===5?'Principios de diseño · Controles por implementar':'Demostración ilustrativa · Sin captura ni envío real'}</span><span>{String(scene+1).padStart(2,'0')} / {String(scenes.length).padStart(2,'0')}</span></footer>
    </div>
    {notes&&!recording&&<aside className="speaker-notes"><span className="eyebrow">LOCUCIÓN · {clock(starts[scene])}—{clock(starts[scene]+current.duration)}</span><p>{current.notes}</p><small>Locución del módulo 2 del Pitch Maestro. Las duraciones son una pauta para ensayar.</small></aside>}
    <nav className="pitch-timeline pitch-timeline-seven" aria-label="Escenas del pitch">{scenes.map((s,i)=><button key={s.title} className={scene===i?'active':''} aria-current={scene===i?'step':undefined} onClick={()=>jump(i)}><small>{clock(starts[i])}</small><span>{s.title}</span></button>)}</nav>
    <div className="pitch-controls"><button className="text-button" disabled={scene===0} onClick={()=>jump(scene-1)}><ChevronLeft size={19}/>Anterior</button><div><span>{clock(elapsed)} / 5:00</span><button className="secondary" onClick={()=>{if(elapsed>=300){setElapsed(0);setScene(0);}setPlaying(!playing);}}>{playing?<Pause size={16}/>:<Play size={16}/>} {playing?'Pausar pauta':'Reproducir pauta'}</button></div><button className="text-button" onClick={()=>jump(scene===scenes.length-1?0:scene+1)}>{scene===scenes.length-1?'Reiniciar':'Siguiente'}<ChevronRight size={19}/></button></div>
    {recording&&<button className="exit-recording" onClick={()=>onRecording(false)}><X size={16}/>Salir del modo grabación <kbd>Esc</kbd></button>}
  </section>;
}
